#!/bin/bash 

# make it easier to setup masterslave
# enter ip of ros master as arg 

export ROS_MASTER_URI=http://$1:11311
echo "ROS master: $ROS_MASTER_URI" 

export ROS_IP=$(hostname -I)
echo "ROS IP: $ROS_IP"

exec "$@"