Odom/GuessMotion: 'false' 
# Vis/BundleAdjustment: 1
Vis/CorType: 1 # 0=Features Matching, 1=Optical Flow
Vis/CorFlowEps: 0.01 
Vis/CorFlowIterations: 30 
Vis/CorFlowMaxLevel: 3  
Vis/CorFlowWinSize: 32 
Vis/CorGuessWinSize: 40
Vis/EstimationType: 0
# Vis/FeatureType: 0
# [0=SURF 1=SIFT 2=ORB 3=FAST/FREAK 4=FAST/BRIEF 5=GFTT/FREAK 6=GFTT/BRIEF 7=BRISK 8=GFTT/ORB 9=KAZE 
Vis/InlierDistance: 0.8 
Vis/MinInliers: 2 
Odom/ResetCountdown: 8